version: 2
updates:
  - package-ecosystem: gomod
    directories:
      - "**/*"
    schedule:
      interval: weekly
    assignees:
      - mikelamutxastegi
    commit-message:
      prefix: "chore"
      include: scope
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch
  - package-ecosystem: docker
    directory: "/ci"
    schedule:
      interval: weekly
    assignees:
      - mikelamutxastegi
    commit-message:
      prefix: "chore"
      include: scope
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    assignees:
      - mikelamutxastegi
    commit-message:
      prefix: "chore"
      include: scope
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch
