coverage:
  status:
    project:
      default: off
      shared-aws:
        target: auto
        flags:
        - shared-aws
      shared-http:
        target: auto
        flags:
        - shared-http
      shared-subsystems:
        target: auto
        flags:
        - shared-subsystems
      core:
        target: auto
        flags: 
        - core
      sdk:
        target: auto
        flags:
        - sdk
      crypto-aws:
        target: auto
        flags: 
        - crypto-aws
      crypto-filesystem:
        target: auto
        flags: 
        - crypto-filesystem
      crypto-vaultkv2:
        target: auto
        flags: 
        - crypto-vaultkv2
      crypto-pkc11:
        target: auto
        flags: 
        - crypto-pkcs11
      storage-postgres:
        target: auto
        flags: 
        - storage-postgres
      eventbus-amqp:
        target: auto
        flags: 
        - eventbus-amqp
      eventbus-aws:
        target: auto
        flags: 
        - eventbus-aws
      backend:
        target: auto
        flags:
        - backend
      backend-assemblers-ca:
        target: auto
        flags:
        - backend-assemblers-ca
      backend-assemblers-kms:
        target: auto
        flags:
        - backend-assemblers-kms
      backend-assemblers-va:
        target: auto
        flags:
        - backend-assemblers-va
      backend-assemblers-device-manager:
        target: auto
        flags:
        - backend-assemblers-device-manager
      backend-assemblers-dms-manager:
        target: auto
        flags:
        - backend-assemblers-dms-manager
      backend-assemblers-alerts:
        target: auto
        flags:
        - backend-assemblers-alerts
      connector-awsiot:
        target: auto
        flags:
        - connector-awsiot
      monolithic:
        target: auto
        flags:
        - monolithic
    patch: off

flags:
  shared-aws:
    paths:
        - shared/aws/
    carryforward: true
  shared-http:
    paths:
        - shared/http/
    carryforward: true
  shared-subsystems:
    paths:
        - shared/subsystems/
    carryforward: true
  core:
    paths:
        - core/
    carryforward: true
  sdk:
    paths:
        - sdk/
    carryforward: true
  crypto-aws:
    paths:
        - engines/crypto/aws/
    carryforward: true
  crypto-filesystem:
    paths:
        - engines/crypto/filesystem/
    carryforward: true
  crypto-vaultkv2:
    paths:
        - engines/crypto/vaultkv2/
    carryforward: true
  crypto-pkcs11:
    paths:
        - engines/crypto/pkcs11/
    carryforward: true
  storage-postgres:
    paths:
        - engines/storage/postgres/
    carryforward: true
  eventbus-amqp:
    paths:
        - engines/eventbus/amqp/
    carryforward: true
  eventbus-aws:
    paths:
        - engines/eventbus/aws/
    carryforward: true
  backend:
    paths:
        - backend/
    carryforward: true
  backend-assemblers-ca:
    paths:
        - backend/
    carryforward: true
  backend-assemblers-kms:
    paths:
        - backend/
    carryforward: true
  backend-assemblers-va:
    paths:
        - backend/
    carryforward: true
  backend-assemblers-device-manager:
    paths:
        - backend/
    carryforward: true
  backend-assemblers-dms-manager:
    paths:
        - backend/
    carryforward: true
  backend-assemblers-alerts:
    paths:
        - backend/
    carryforward: true
  connector-awsiot:
    paths:
        - connectors/awsiot/
    carryforward: true
  monolithic:
    paths:
        - monolithic/
    carryforward: true

ignore:
  - "**/*_mock.go"
  - "**/*_test.go"
  - "**/*_testset.go"
  - "**/test/*"
  - "**/test/**/*"
  - "**/subsystem/*"
  - "**/subsystem/**/*"
  - "**/docker/**/*"
  - "**/docker/*"
  - "**/dockerrunner/**/*"
  - "**/dockerrunner/*"

