sonar.projectKey=lks-ot-i-plus-d_lamassuiot
sonar.organization=lks-ot-i-plus-d


# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=Lamassuiot
sonar.projectVersion=1.0


sonar.sources=backend
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage-reports/**/coverage.out
# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Code Coverage
sonar.coverage.exclusions=**/*_test.go,**/test/**,**/*_test.go

# Duplications
sonar.cpd.exclusions=**/main.go,**/backend/pkg/middlewares/**/*.go,**/monolithic/pkg/sampledata/*.go,**/*.sql

# Files
sonar.exclusions=**/*_test.go,**/vendor/**,**/test/**,**/testdata/**,**/testutil/**

# Test Files 
sonar.test.exclusions=**/*_test.go,**/vendor/**,**/test/**,**/testdata/**,**/testutil/**

# Go
sonar.go.file.suffixes=.go
sonar.go.exclusions=**/vendor/**,**/*_test.go,**/test/**,**/*_mock.go
