name: Build experimental features 

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Build with experimental features
    runs-on: ubuntu-latest
    outputs:
      coverage: ${{ steps.run.outputs.coverage }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.20.0' # The Go version to download (if necessary) and use.

      - name: Install Dependencies
        run: go mod download

      - name: Build wiht experimental features
        run: go build -tags experimental ./cmd/monolithic/development/main.go