name: Bump Go Version

on:
  workflow_dispatch:
    inputs:
      go_version:
        type: string
        description: go version to use (example; 1.20.1)


jobs:
  bumper:
    name: Bump Go version and open PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create commits
        run: |
          git config user.name 'Lamassu GH Action'
          git config user.email 'lamassu-action@users.noreply.github.com'

          # Update the Go version in the go.mod file
          sed -i '' "s/go [0-9.]*$/go ${{ github.event.inputs.release_version }}/" go.mod

          dockerfiles=$(find . -type f -name "*.dockerfile")
          # Loop through each Dockerfile and update the Go version
          for dockerfile in $dockerfiles; do
              # Update the Go version in Dockerfile
              sed -i '' "s/golang:[0-9.]*-/golang:${{ github.event.inputs.release_version }}-/" Dockerfile
              
              echo "Updated Dockerfile: $dockerfile"
          done

          git commit -s -am "Bump go version to ${{ github.event.inputs.release_version }}" 
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Bumping go version to ${{ github.event.inputs.release_version }}"
          branch: "bump-go-version-${{ github.event.inputs.release_version }}"
          base: main
  