name: "DEV Release Workflow: (ONLY creates docker images with dev tag)"

on:
  workflow_dispatch:

jobs:
  build_docker_image:
    needs: [create_tag, version_info]
    strategy:
      matrix:
        service: [ca, devmanager, dmsmanager, va, alerts, aws-connector]
    name: ${{ matrix.service }} - Release docker images
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
      - run: |
          echo "SHA1VER=dev-$(git rev-parse HEAD)" >> $GITHUB_ENV
          
      - name: Login to Github Registry
        uses: docker/login-action@v3 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build ${{ matrix.service }} DEV docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ci/${{ matrix.service }}.dockerfile
          build-args: |
            BASE_IMAGE=alpine:3.14
            SHA1VER=${{ env.SHA1VER }}
            VERSION=dev
          tags: |
            ghcr.io/lamassuiot/lamassu-${{ matrix.service }}:dev
          push: true
