name: "Update README test coverage badge"

on:
  push:
    branches:
      - 'main'

jobs:
  run_tests:
    name: Run Tests
    uses: ./.github/workflows/ci-test.yaml
  update_badge:
    runs-on: ubuntu-latest
    name: Update Badge
    needs:
      - run_tests
    steps:
    - name: obtain coverage and hex color
      id: cov_hex
      shell: bash
      run: |
        coverage=$(printf '%.0f' "${{ needs.run_tests.outputs.coverage }}")
        R=$(((255*(100-$coverage))/100))
        G=$(((255*$coverage)/100))
        B=0
        hex=$(printf '%02x%02x%02x\n' $R $G $B)

        echo "coverage=$coverage" >> $GITHUB_OUTPUT
        echo "hex=$hex" >> $GITHUB_OUTPUT
    - uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_COVERAGE }}
        gistID: a1936540297c6e96589da704a71419be
        filename: coverage.json # Use test.svg if you want to use the SVG mode.
        label: Coverage
        message: ${{ steps.cov_hex.outputs.coverage }}%
        color:  ${{ steps.cov_hex.outputs.hex }}
