name: "Pin Check: verify all GitHub Actions are pinned to commit SHAs"

permissions:
  contents: read

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/*.yaml"

jobs:
  pinact:
    name: Verify pinned actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Verify all actions are pinned to full commit SHAs
        uses: suzuki-shunsuke/pinact-action@896d595f299e71d65b9d28349d6956abe144390a # v3.0.0
        with:
          skip_push: "true"
          fix: "false"
