name: "Release Workflow - Open Pull Request with release notes"

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      release_version:
        type: string
        description: release version when building docker containers (example; 2.0.0)

run-name: >-
  ${{ format('Open PR for release {0}', github.event.inputs.release_version) }}

jobs:
  open_pr:
    name: "Open PR with release notes and changelog"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        uses: orhun/git-cliff-action@3d96a18cc4ec17e9dc69ddcc424ccafaf1f78ce2 # v4.9.0
        with:
          version: v2.14.1
          args: --tag v${{ github.event.inputs.release_version }}
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Generate release notes
        uses: orhun/git-cliff-action@3d96a18cc4ec17e9dc69ddcc424ccafaf1f78ce2 # v4.9.0
        with:
          version: v2.14.1
          args: --unreleased --tag v${{ github.event.inputs.release_version }}
        env:
          OUTPUT: RELEASE-NOTES.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Read generated files
        id: read-files
        run: |
          echo "release-notes<<EOF" >> $GITHUB_OUTPUT
          cat RELEASE-NOTES.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore: release: prepare release ${{ github.event.inputs.release_version }}"
          branch: "release-${{ github.event.inputs.release_version }}"
          title: "chore: release: prepare release ${{ github.event.inputs.release_version }}"
          sign-commits: true
          body: |
            # Release ${{ github.event.inputs.release_version }}

            ## Release Notes

            ${{ steps.read-files.outputs.release-notes }}